--Drop, Create, Alter
DROP TABLE VZTOOL.CLOBTABLE ;
--Create table
CREATE TABLE VZTOOL.CLOBTABLE ( 
   COL0 DECIMAL (7, 0),
   COL1 NCLOB (1M),
   COL2 CLOB (1M) CCSID 1208,
   COL3 DBCLOB CCSID 13488
)
