--Vytvoříme tabulku SOUCASTI v knihovně KOLEKCE
SET SCHEMA KOLEKCE;

-- Smažeme tabulku SOUCASTI
-- DROP TABLE SOUCASTI;  /* To už nepotřebujeme, máme slovo REPLACE

--Pro kusovník vytvoříme tabulku SOUCASTI
CREATE OR REPLACE TABLE SOUCASTI   
  ( SOUCAST CHAR (2), PODSOUCAST CHAR(2), POCET SMALLINT )
;

INSERT INTO SOUCASTI VALUES('A', 'B', 3);
INSERT INTO SOUCASTI VALUES('A', 'C', 3);
INSERT INTO SOUCASTI VALUES('B', 'E', 2);
INSERT INTO SOUCASTI VALUES('E', 'C', 2);
INSERT INTO SOUCASTI VALUES('E', 'D', 3);
INSERT INTO SOUCASTI VALUES('E', 'F', 5);
INSERT INTO SOUCASTI VALUES('C', 'D', 4);
INSERT INTO SOUCASTI VALUES('C', 'F', 4)
; 
SET SCHEMA DEFAULT
