--Sales by day-of-week, week, and grand-total

--;T B1 ; A1 ;  ; S3 ; week;

SELECT WEEK(SALES_DATE) AS WEEK, 
  DAYOFWEEK(SALES_DATE) AS DAY_WEEK, 
  SUM(SALES) AS UNITS_SOLD
FROM SALES
GROUP BY ROLLUP( WEEK(SALES_DATE), DAYOFWEEK(SALES_DATE) )
ORDER BY WEEK, DAY_WEEK
