--Seznam zboží ve stavech, které mělo nějaký obrat
SELECT DISTINCT C.CZBOZI, C.NAZZBO, S.CZBOZI, O.CZBOZI Z_OBRATU
FROM CENY C
   INNER JOIN STAVY S ON C. CZBOZI = S. CZBOZI
   INNER JOIN OBRATY O ON S. CZBOZI = O. CZBOZI
