--UserDoc 
--;D  ; SOUCET ;
--;D 0000000.000 ; PRUMER ;
SELECT S.ZAVOD, S.SKLAD,     
      DECIMAL( SUM(C.CENAJ*S.MNOZSTVI), 9, 2 ) AS SOUCET,
      INT( AVG(C.CENAJ*S.MNOZSTVI) ) as PRUMER,
      INT( MIN( C.CENAJ*S.MNOZSTVI) ) as MIN,
      INT( MAX( C.CENAJ*S.MNOZSTVI) ) as MAXIMUM
FROM STAVY AS S
   JOIN CENY AS C ON S.CZBOZI = C.CZBOZI
   GROUP BY ROLLUP( S.ZAVOD, S.SKLAD )
   ORDER BY S.ZAVOD, S.SKLAD
