--Create table PRICES with UTF-8 columns

DROP TABLE VZTOOL.PRICES
;

CREATE TABLE VZTOOL.PRICES
   ( CZBOZI CHAR(5), 
     CENAJ DEC(12, 2),
     NAZZBO CHAR(50) CCSID 1208
   )
;

SET SCHEMA DEFAULT
